[shell]
program = "/usr/bin/bash"
args = ["--login"]


[window]
dimensions = { columns = 150, lines = 40 }
padding = { x = 1, y = 1 }
dynamic_padding = true
opacity = 0.9
blur = true
startup_mode = "Windowed"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#282c34"
foreground = "#bbc2cf"

[colors.bright]
black = "#5b6268"
blue = "#3071db"
cyan = "#46d9ff"
green = "#4db5bd"
magenta = "#a9a1e1"
red = "#da8548"
white = "#dfdfdf"
yellow = "#ecbe7b"

[colors.cursor]
cursor = "#528bff"
text = "CellBackground"

[colors.normal]
black = "#1c1f24"
blue = "#51afef"
cyan = "#5699af"
green = "#98be65"
magenta = "#c678dd"
red = "#ff6c6b"
white = "#abb2bf"
yellow = "#da8548"

[colors.selection]
background = "#3e4451"
text = "CellForeground"

[env]
TERM = "xterm-256color"
